export interface student1
{
    sid:number;
    sname:string;
    srank:number;
    sschool:string;
    id:number;
    name:string;
    rank:number;
    school:string;
    id1:number;
    name1:string;
    rank1:number;
    school1:string;
    id2:number;
    name2:string;
    rank2:number;
    school2:string;
}